# Generated by Django 6.0.3 on 2026-04-01 00:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id_0', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Géométrie')),
                ('id', models.BigIntegerField(blank=True, null=True, verbose_name='ID original')),
                ('nom', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nom')),
                ('est', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Est')),
                ('nord', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Nord')),
                ('altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Altitude')),
                ('ordre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ordre')),
                ('localite', models.CharField(blank=True, max_length=254, null=True, verbose_name='Localité')),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Point géodésique',
                'verbose_name_plural': 'Points géodésiques',
                'db_table': 'public.points',
                'managed': False,
            },
        ),
    ]
